 warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/usr/local/lib/python3.8/dist-packages/mmdet/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
projects.mmdet3d_plugin
Using /root/.cache/torch_extensions/py38_cu111 as PyTorch extensions root...
Creating extension directory /root/.cache/torch_extensions/py38_cu111/dvr...
/usr/local/lib/python3.8/dist-packages/mmdet/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
projects.mmdet3d_plugin
Using /root/.cache/torch_extensions/py38_cu111 as PyTorch extensions root...
/usr/local/lib/python3.8/dist-packages/mmdet/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
projects.mmdet3d_plugin
Using /root/.cache/torch_extensions/py38_cu111 as PyTorch extensions root...
Traceback (most recent call last):
  File "tools/test.py", line 290, in <module>
    main()
  File "tools/test.py", line 171, in main
    plg_lib = importlib.import_module(_module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/__init__.py", line 1, in <module>
    from .datasets import *
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/datasets/__init__.py", line 2, in <module>
    from .nuscenes_dataset_occ import NuScenesDatasetOccpancy
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 13, in <module>
    from ..core.evaluation.ray_metrics import main as calc_rayiou
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/core/evaluation/ray_metrics.py", line 13, in <module>
    dvr = load("dvr", sources=["lib/dvr/dvr.cpp", "lib/dvr/dvr.cu"], verbose=True, extra_cuda_cflags=['-allow-unsupported-compiler'])
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1418, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1474, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
/usr/local/lib/python3.8/dist-packages/mmdet/utils/setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
projects.mmdet3d_plugin
Using /root/.cache/torch_extensions/py38_cu111 as PyTorch extensions root...
Traceback (most recent call last):
  File "tools/test.py", line 290, in <module>
    main()
  File "tools/test.py", line 171, in main
    plg_lib = importlib.import_module(_module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/__init__.py", line 1, in <module>
    from .datasets import *
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/datasets/__init__.py", line 2, in <module>
    from .nuscenes_dataset_occ import NuScenesDatasetOccpancy
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 13, in <module>
    from ..core.evaluation.ray_metrics import main as calc_rayiou
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/core/evaluation/ray_metrics.py", line 13, in <module>
    dvr = load("dvr", sources=["lib/dvr/dvr.cpp", "lib/dvr/dvr.cu"], verbose=True, extra_cuda_cflags=['-allow-unsupported-compiler'])
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1418, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1474, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
Loading extension module dvr...
Traceback (most recent call last):
  File "tools/test.py", line 290, in <module>
    main()
  File "tools/test.py", line 171, in main
    plg_lib = importlib.import_module(_module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/__init__.py", line 1, in <module>
    from .datasets import *
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/datasets/__init__.py", line 2, in <module>
    from .nuscenes_dataset_occ import NuScenesDatasetOccpancy
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 13, in <module>
    from ..core.evaluation.ray_metrics import main as calc_rayiou
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/core/evaluation/ray_metrics.py", line 13, in <module>
    dvr = load("dvr", sources=["lib/dvr/dvr.cpp", "lib/dvr/dvr.cu"], verbose=True, extra_cuda_cflags=['-allow-unsupported-compiler'])
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1362, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1752, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /root/.cache/torch_extensions/py38_cu111/dvr/dvr.so: cannot open shared object file: No such file or directory
Loading extension module dvr...
Traceback (most recent call last):
  File "tools/test.py", line 290, in <module>
    main()
  File "tools/test.py", line 171, in main
    plg_lib = importlib.import_module(_module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/__init__.py", line 1, in <module>
    from .datasets import *
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/datasets/__init__.py", line 2, in <module>
    from .nuscenes_dataset_occ import NuScenesDatasetOccpancy
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/datasets/nuscenes_dataset_occ.py", line 13, in <module>
    from ..core.evaluation.ray_metrics import main as calc_rayiou
  File "/workspace/flashocc/FlashOCC/projects/mmdet3d_plugin/core/evaluation/ray_metrics.py", line 13, in <module>
    dvr = load("dvr", sources=["lib/dvr/dvr.cpp", "lib/dvr/dvr.cu"], verbose=True, extra_cuda_cflags=['-allow-unsupported-compiler'])
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1362, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1752, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /root/.cache/torch_extensions/py38_cu111/dvr/dvr.so: cannot open shared object file: No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 327) of binary: /usr/local/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/test.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-29_15:53:40
  host      : c97896ebe33a
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 328)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-10-29_15:53:40
  host      : c97896ebe33a
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 329)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-10-29_15:53:40
  host      : c97896ebe33a
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 330)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-29_15:53:40
  host      : c97896ebe33a
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 327)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
